test-data-set:
	./cli create device -n "Test Device"
	./cli create test-session -n "Test Test Session" -d 1
	./cli create condition -n "Test Condition"
	./cli create condition-value -v "Test Condition Value" -c 1
	./cli create scenario -n "Test Scenario" -t 1 -c 1